version: "2"
services:
  nginx:
    container_name: webserver-iot
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    ports:
      - "81:80"
      - "444:443"
    depends_on:
      - nodeapp-iot
  nodeapp-iot:
    container_name: nodeapp-iot
    restart: always
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - mongo-server-iot      
  mongo-server-iot:
    container_name: mongo-server-iot
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"

